version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
        environment:
          FLASK_CONFIG: testing
    steps:
      - working_directory: ~/flydu-weather-data
      - add_ssh_keys:
          fingerprints:
            - "f3:e1:24:7a:b9:2e:61:73:23:e3:fa:f6:76:b2:a3:8f"
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV
            virtualenv helloworld
            . helloworld/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate
            python test_hello_world.py
      - run:
          name: Transfer Files to Server via SCP
          command: |
            scp -r ~/flydu-weather-data "$SSH_USER@$SSH_HOST:$SSH_DEPLOYPATH"

     # - run:
     #     name: Deploy app to Flyingdutchman Server via Docker
     #     command: |
     #       ssh -o StrictHostKeyChecking=no circleci@144.91.126.223 "/bin/bash ./deploy_app.sh ariv3ra/$IMAGE_NAME:$TAG"