version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
        environment:
          FLASK_CONFIG: testing
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f3:e1:24:7a:b9:2e:61:73:23:e3:fa:f6:76:b2:a3:8f"
      - checkout
      #- run:
      #    name: Setup VirtualEnv
      #    command: |
      #      echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
      #      echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV
      #      virtualenv helloworld
      #      . helloworld/bin/activate
      #      pip install --no-cache-dir -r requirements.txt
      - run:
          name: Add Target Node to known hosts
          command: |
            sudo ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      #- run:
      #    name: Run Tests
      #    command: |
      #      . helloworld/bin/activate
      #      python hello_world_test.py
      - run:
          name: Transfer Files to Server via SCP
          command: |
            scp -r * "$SSH_USER@$SSH_HOST:$SSH_DEPLOYPATH"

     # - run:
     #     name: Deploy app to Flyingdutchman Server via Docker
     #     command: |
     #       ssh -o StrictHostKeyChecking=no circleci@144.91.126.223 "/bin/bash ./deploy_app.sh ariv3ra/$IMAGE_NAME:$TAG"
      - run:
          name: Build Docker Image on Flyingdutchman Node
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cat 'blablablabla' > $SSH_DEPLOYPATH/deploytest.txt"